import Head from "next/head";
import axios from "axios";
import { Item, Section } from "@/types";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import { HomeScreen, ItemScreen } from "@/screens";
import { Cart } from "@/components";

const apiUrl = process.env.NEXT_PUBLIC_API_URL;

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: true,
  };
}

export const getStaticProps = async ({ params }: any) => {
  const { username } = params;
  const { data: sections } = await axios.get(`${apiUrl}/sections`);
  const { data: items } = await axios.get(`${apiUrl}/items`);
  const { data: advertisings } = await axios.get(`${apiUrl}/advertisings`);

  return { props: { username, sections, items, advertisings } };
};

type props = {
  username: string;
  sections: Array<Section>;
  items: Array<Item>;
  advertisings: Array<any>;
};

export default function Index({
  username,
  sections,
  items,
  advertisings,
}: props) {
  return (
    <>
      <Head>
        <title>Pizza Burguer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Cart />
        <BrowserRouter basename={`/pizza-burguer/${username}`}>
          <Routes>
            <Route
              path="/"
              element={
                <HomeScreen
                  sections={sections}
                  items={items}
                  advertisings={advertisings}
                />
              }
            />
            <Route path="/item/:id" element={<ItemScreen items={items} />} />
          </Routes>
        </BrowserRouter>
      </main>
    </>
  );
}
