import { Flex } from "@chakra-ui/react";
import axios from "axios";
import Head from "next/head";
import { QRCodeCanvas } from "qrcode.react";

const apiUrl = process.env.NEXT_PUBLIC_API_URL;

export const getStaticProps = async () => {
  const { data: qrCode } = await axios.get(`${apiUrl}/whatsapp`);

  return { props: { qrCode } };
};

type props = {
  qrCode: { qr: string };
};

export default function Index({ qrCode }: props) {
  return (
    <>
      <Head>
        <title>Pizza Burguer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex w="100vw" h="100vh" align="center" justify="center">
          <QRCodeCanvas size={256} value={qrCode.qr} level="H" />
        </Flex>
      </main>
    </>
  );
}
