import Head from "next/head";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { Item, Section } from "@/types";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import { HomeScreen, ItemScreen } from "@/screens";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"], display: "swap" });

const apiUrl = process.env.NEXT_PUBLIC_API_URL;

export const getStaticProps = async () => {
  const { data: sections } = await axios.get(`${apiUrl}/sections`);
  const { data: items } = await axios.get(`${apiUrl}/items`);
  const { data: advertisings } = await axios.get(`${apiUrl}/advertisings`);

  return { props: { sections, items, advertisings } };
};

type props = {
  sections: Array<Section>;
  items: Array<Item>;
  advertisings: Array<any>;
};

export default function Index({ sections, items, advertisings }: props) {
  return (
    <>
      <Head>
        <title>Pizza Burguer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <BrowserRouter>
          <Routes>
            <Route
              path="/"
              element={
                <HomeScreen
                  sections={sections}
                  items={items}
                  advertisings={advertisings}
                />
              }
            />
            <Route path="/item/:id" element={<ItemScreen items={items} />} />
          </Routes>
        </BrowserRouter>
      </main>
    </>
  );
}
