import Head from "next/head";
import { Item, Section } from "@/types";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import { HomeScreen, ItemScreen } from "@/screens";
import { Cart } from "@/components";
import { sectionRepository } from "@/db/repositories";
import { itemRepository } from "@/db/repositories/item";
import { advertisingRepository } from "@/db/repositories/advertising";
import { Notify } from "@/components/organisms";

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: true,
  };
}

type staticProps = { params: { username: string } };

export const getStaticProps = async ({ params }: staticProps) => {
  const { username } = params;
  const sections = await sectionRepository.getSections();
  const items = await itemRepository.getItems();
  const advertisings = await advertisingRepository.getAdvertisings();

  return { props: { username, sections, items, advertisings } };
};

type props = {
  username: string;
  sections: Array<Section>;
  items: Array<Item>;
  advertisings: Array<any>;
};

export default function Index(props: props) {
  const { username, sections, items, advertisings } = props;

  return (
    <>
      <Head>
        <title>Pizza Burguer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Notify />
        <Cart username={username} />
        <BrowserRouter basename={`/wpp/${username}`}>
          <Routes>
            <Route
              path="/"
              element={
                <HomeScreen
                  sections={sections}
                  items={items}
                  advertisings={advertisings}
                />
              }
            />
            <Route path="/item/:id" element={<ItemScreen items={items} />} />
          </Routes>
        </BrowserRouter>
      </main>
    </>
  );
}
